# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 02:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restusers_app', '0002_user_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='dateAdded',
            new_name='created_at',
        ),
    ]
